version: '2.0'
services:
  rasa:
    image: rasa_tuyensinh:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./data:/app/data
    - ./actions:/app/actions
    - ./tests:/app/tests
  
    command: bash -c "rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\""
    ports:
    - '5006:5005'
    networks:
    - all

  rasa-actions:
    image: rasa_tuyensinh:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"